### ISSUE TITLE
fix dynmap

### ISSUE THREAD

**Issue by JohnHeikens** [JohnHeikens/Axo#62]

**Comment by JohnHeikens** [comment]
give dynmap an ssl certificate

**Comment by Blitheness** [comment]
You can set up an nginx reverse proxy that serves your map over a secure connection. Use LetsEncrypt to create a free certificate.

https://github.com/webbukkit/dynmap/wiki/Nginx-as-a-Reverse-Proxy

You could cache map tiles on the web server so each user isn't directly hitting the Minecraft server. If you use nginx cache, create an upstream block (using a keepalive param, maybe 12?) in your site configuration to limit the number of connections, otherwise you may find that your map appears to stop showing tile images.

**Comment by JohnHeikens** [comment]
@Blitheness first of all, hi? lol
i never saw you here! if you're new here consider joining our discord, i'd be interested to talk with you :smiley: 
https://discord.gg/YYVscyAKU4
second of all, i just set up an inverse proxy. and the map is locked away and our server is one of the most performant servers in the world so we don't have to worry about usage brag brag ok imma shut up now lol
